### ISSUE TITLE
Add introspection API

### ISSUE THREAD

**Issue by blochberger** [AppPETs/PrivacyService#2]
In order to visualize/demonstrate the knowledge of the P-Service operator an introspection API is required, where the whole database can be retrieved.

This issue was migrated from https://gitlab.prae.me/apppets/PrivacyService/issues/2.

**Comment by 0xbf00** [comment]
I'm currently working on this. The whole database is unlikely to be of much help, as it also includes old values and long-forgotten requests data.

As a start, the following data might make sense:
- key used
- size of value in bytes (the actual value can be many megabytes in size)
- ip address of request (last update to value only)
- headers of request (last update to value only)
- datetime of last update

However, it might not be appropriate to output the access key as part of a publicly accessible API as attackers could simply query all available keys and delete all data. (@blochberger)

**Comment by blochberger** [comment]
The introspection API should return the current state of the DB. That way it can be used to show, if items where removed or changed.

> However, it might not be appropriate to output the access key as part of a publicly accessible API as attackers could simply query all available keys and delete all data.

I think that's fine, as the service is for demonstration purposes only. If someone decides to troll us this way, we can simply hash the keys before returning them.

**Comment by 0xbf00** [comment]
An introspection API at `/storage/v1/dump` is now available.

It returns a JSON representation of the database. For each key `k` of the key-value store, both current and historical data is returned:

```json
{
  "ffff...": {
    "current": {
      "timestamp": "2018-08-20 12:15:30.761491",
      "headers": [ { "key": "Connection", "value": "keep-alive" } ],
      "ip": "127.0.0.1",
      "size": 42
    },
    "history": [{
      "timestamp": "2018-08-19 14:11:31.363199",
      ...
      }, ...]
  },
  ...
}
```

In case no value is currently associated with key `k`, the `current` key maps to `null`. All entries contain the `timestamp`, `headers`, `ip` and `size` attribute.
