### ISSUE TITLE
Enable adversarial behavior only if a specific header is set

### ISSUE THREAD

**Issue by blochberger** [AppPETs/PrivacyService#5]
In order to avoid tracking every request, the service should only track requests, where a specific header, e.g., `X-AppPETs-BadProvider: 1` is set. This header then acts as a tracking consent. This feature is used for demonstration purposes only.

**Comment by 0xbf00** [comment]
Code on `master` now only logs requests with the `X-AppPETs-BadProvider` header set to a non-zero value.
